import { HardHat, Ruler, Briefcase, Layers, PenTool, BarChart2, Shield, ClipboardCheck, DollarSign, Eye, Waves, Building2, Droplets, Factory, Wrench, GitBranch, FlaskConical, FileText, FileSearch } from 'lucide-react';

// ─── Non-buyable parent categories (tabs / organisational) ───────────────────
export const SERVICE_CATEGORIES = [
  {
    id: 'construction',
    title: 'Construction',
    Icon: HardHat,
    summary: 'Implementation of heavy-duty urban and industrial infrastructure at scale.',
  },
  {
    id: 'consultancy',
    title: 'Consultancy',
    Icon: Ruler,
    summary: 'Precision-driven strategic engineering advisory and detailed technical design.',
  },
  {
    id: 'project-management',
    title: 'Project Management',
    Icon: Briefcase,
    summary: 'End-to-end execution, supervision, and full lifecycle management of civil projects.',
  },
] as const;

// ─── Buyable child services (each links to a parent category) ────────────────
export const CHILD_SERVICES = [
  // ── Construction ──────────────────────────────────────────────────────────
  {
    id: 'roadworks',
    categoryId: 'construction',
    title: 'Roadworks',
    Icon: Layers,
    summary: 'Urban and rural road construction including sub-base preparation, surfacing and kerbing.',
    details: ['Sub-base & Base Course', 'Asphalt Surfacing', 'Kerb & Channel', 'Line Marking'],
    price: 15000,
  },
  {
    id: 'sewer-reticulation',
    categoryId: 'construction',
    title: 'Sewer Reticulation',
    Icon: Waves,
    summary: 'Full installation of gravity sewer networks, manholes and pump stations.',
    details: ['Gravity Sewer Mains', 'Manhole Construction', 'Pump Station Installation', 'CCTV Inspection'],
    price: 15000,
  },
  {
    id: 'reservoir-construction',
    categoryId: 'construction',
    title: 'Reservoir Construction',
    Icon: Droplets,
    summary: 'Design and construction of reinforced concrete water storage reservoirs.',
    details: ['RC Tank Design', 'Foundation Works', 'Waterproofing', 'Commissioning'],
    price: 15000,
  },
  {
    id: 'structural-works',
    categoryId: 'construction',
    title: 'Structural Works',
    Icon: Building2,
    summary: 'Heavy structural construction for commercial, industrial and institutional buildings.',
    details: ['Reinforced Concrete Frames', 'Masonry & Blockwork', 'Steel Fabrication', 'Formwork & Shuttering'],
    price: 15000,
  },
  {
    id: 'waste-stabilisation-ponds',
    categoryId: 'construction',
    title: 'Waste Stabilisation Ponds',
    Icon: Factory,
    summary: 'Construction of engineered waste-water treatment ponds for municipal and industrial use.',
    details: ['Earthworks & Lining', 'Inlet/Outlet Structures', 'Effluent Monitoring', 'Commissioning'],
    price: 15000,
  },
  {
    id: 'highway-construction',
    categoryId: 'construction',
    title: 'Highway Construction',
    Icon: HardHat,
    summary: 'Large-scale highway and arterial road implementation with full civil works.',
    details: ['Earthworks & Grading', 'Asphalt Laying', 'Drainage Structures', 'Traffic Management'],
    price: 15000,
  },
  // ── Consultancy ───────────────────────────────────────────────────────────
  {
    id: 'feasibility-studies',
    categoryId: 'consultancy',
    title: 'Feasibility Studies',
    Icon: FileSearch,
    summary: 'Comprehensive technical and economic feasibility assessments for proposed projects.',
    details: ['Site Investigation', 'Economic Analysis', 'Risk Assessment', 'Recommendation Report'],
    price: 15000,
  },
  {
    id: 'hydraulic-modeling',
    categoryId: 'consultancy',
    title: 'Hydraulic Modeling',
    Icon: Waves,
    summary: 'Advanced computational hydraulic analysis for water supply and drainage systems.',
    details: ['Network Simulation', 'Flood Routing', 'Pressure Zone Analysis', 'Calibration & Reporting'],
    price: 15000,
  },
  {
    id: 'detailed-design',
    categoryId: 'consultancy',
    title: 'Detailed Design',
    Icon: PenTool,
    summary: 'Full engineering drawings and specifications ready for tender and construction.',
    details: ['CAD / BIM Drawings', 'Structural Calculations', 'Specifications', 'Bill of Quantities'],
    price: 15000,
  },
  {
    id: 'contract-administration',
    categoryId: 'consultancy',
    title: 'Contract Administration',
    Icon: FileText,
    summary: 'Professional oversight of construction contracts from award through to final account.',
    details: ['Tender Evaluation', 'Progress Certification', 'Variation Management', 'Final Account Settlement'],
    price: 15000,
  },
  {
    id: 'structural-analysis',
    categoryId: 'consultancy',
    title: 'Structural Analysis',
    Icon: FlaskConical,
    summary: 'Finite element and hand-calculation structural analysis to BS/SANS/EN standards.',
    details: ['Load Analysis', 'FEA Modelling', 'Peer Review', 'Certification'],
    price: 15000,
  },
  {
    id: 'bridge-design',
    categoryId: 'consultancy',
    title: 'Bridge Design',
    Icon: GitBranch,
    summary: 'Advanced structural design for urban and rural bridge and culvert infrastructure.',
    details: ['Structural Analysis', 'Load Testing', 'Material Specification', 'Construction Drawings'],
    price: 15000,
  },
  // ── Project Management ────────────────────────────────────────────────────
  {
    id: 'project-planning',
    categoryId: 'project-management',
    title: 'Project Planning',
    Icon: ClipboardCheck,
    summary: 'Detailed programme development with resource-loaded schedules and milestone tracking.',
    details: ['Work Breakdown Structure', 'Gantt Scheduling', 'Resource Allocation', 'Baseline Programme'],
    price: 15000,
  },
  {
    id: 'risk-mitigation',
    categoryId: 'project-management',
    title: 'Risk Mitigation',
    Icon: Shield,
    summary: 'Systematic identification, analysis and management of project risks throughout the lifecycle.',
    details: ['Risk Register', 'Qualitative Assessment', 'Mitigation Strategies', 'Monthly Monitoring'],
    price: 15000,
  },
  {
    id: 'quality-assurance',
    categoryId: 'project-management',
    title: 'Quality Assurance',
    Icon: Wrench,
    summary: 'Independent QA and QC programmes ensuring construction meets specification and code.',
    details: ['Inspection Test Plans', 'Material Testing', 'Non-Conformance Reporting', 'Audit & Sign-Off'],
    price: 15000,
  },
  {
    id: 'cost-control',
    categoryId: 'project-management',
    title: 'Cost Control',
    Icon: DollarSign,
    summary: 'Budgeting, forecasting and earned-value management to keep projects financially on track.',
    details: ['Budget Establishment', 'Earned Value Analysis', 'Cash-Flow Forecasting', 'Monthly Cost Reports'],
    price: 15000,
  },
  {
    id: 'site-supervision',
    categoryId: 'project-management',
    title: 'Site Supervision',
    Icon: Eye,
    summary: 'Resident engineer and clerk-of-works services ensuring day-to-day compliance on site.',
    details: ['Daily Site Diaries', 'Contractor Coordination', 'Progress Photography', 'Weekly Reports'],
    price: 15000,
  },
  {
    id: 'performance-reporting',
    categoryId: 'project-management',
    title: 'Performance Reporting',
    Icon: BarChart2,
    summary: 'Executive and stakeholder dashboards providing full project transparency and accountability.',
    details: ['KPI Dashboards', 'Schedule Variance', 'Budget vs Actual', 'Stakeholder Reports'],
    price: 15000,
  },
] as const;

export const CONFIG = {
  BRAND: {
    NAME_1: 'CIVIL',
    NAME_2: 'LEGACY',
    TAGLINE: 'Consultancy',
    REGISTRATION: 'ZIE 198098 | ECZ 151080',
  },
  CONTACT: {
    MAIN_LINE: '0718 246 433',
    SECONDARY_LINE: '+263 71 440 6037',
    WHATSAPP_NUM: '263718246433',
    EMAIL: 'info@civillegacy.com',
    OFFICES: [
      { name: 'Headquarters', location: '4248 Avian Way, Northlea, Gweru' },
      { name: 'Chiredzi Branch', location: 'Chiredzi' },
      { name: 'Chipinge Branch', location: '1066 Dam View Mall, Chipinge' },
    ],
    SOCIALS: {
      FACEBOOK: 'https://facebook.com/civillegacy',
      TWITTER: 'https://twitter.com/civillegacy',
      LINKEDIN: 'https://linkedin.com/company/civillegacy',
      INSTAGRAM: 'https://instagram.com/civillegacy',
      TIKTOK: 'https://tiktok.com/@civillegacy',
      WHATSAPP: 'https://wa.me/263718246433',
      EMAIL: 'mailto:info@civillegacy.com',
    },
  },
  PROJECTS: [
    { title: 'Suncoast Project', loc: 'Masvingo', sector: 'Residential', scope: 'Road Design, Water Reticulation, Sewer Reticulation, Stormwater Drainage', stands: '3200 Stands', date: 'Oct 2022', status: 'Completed' },
    { title: 'The Nest of Kenilworth', loc: 'Chipinge', sector: 'Residential', scope: 'Water, Stormwater, Sewer, Road and Public Lighting Design', stands: '3800 Stands', date: 'Nov 2025', status: 'Underway' },
    { title: 'Victoria Range', loc: 'Masvingo', sector: 'Residential', scope: 'Water & Sewer Reticulation Designs', stands: '500 Stands', date: 'Dec 2023', status: 'Completed' },
    { title: 'Boronia Farm Subdivision', loc: 'Harare', sector: 'Residential', scope: 'Water Reticulation Design', stands: '200 Stands', date: 'Mar 2025', status: 'Underway' },
    { title: 'Flamboyant Project', loc: 'Masvingo', sector: 'Residential', scope: 'Water Reticulation Design', stands: '400 Stands', date: 'Jan 2023', status: 'Completed' },
    { title: 'Mutare Recovery Facility', loc: 'Mutare', sector: 'Industrial', scope: 'Full structural design & geotechnical guidance for Industrial Waste Processing Structure', stands: 'Industrial', date: 'Completed', status: 'Completed' },
    { title: 'Madziwa Structural Development', loc: 'Gweru', sector: 'Industrial', scope: 'Full structural design, detailing and documentation for reinforced concrete multi-level building', stands: 'Multi-Storey', date: 'Completed', status: 'Completed' },
    { title: 'Popi Residence', loc: 'Gweru', sector: 'Residential', scope: 'High-end modern residential structural design with reinforced concrete framing and cantilever elements', stands: 'Randolph Phase 1', date: 'Underway', status: 'Underway' },
    { title: 'Proposed Shops & Offices', loc: 'Rusape', sector: 'Commercial', scope: 'Commercial double-storey structural design and reinforcement detailing under BS 8110 standards', stands: 'Stand 2461', date: 'Approved', status: 'Approved' },
    { title: 'Waste Stabilisation Ponds', loc: 'Gweru', sector: 'Infrastructure', scope: 'Design of complete wastewater stabilisation pond system and abattoir effluent treatment', stands: 'Connemara Farm', date: 'Completed', status: 'Completed' },
    { title: 'Fuel Service Station', loc: 'Muzarabani', sector: 'Commercial', scope: 'Commercial structural design of canopy, steel framing and composite infrastructure', stands: 'Energy Park', date: 'Completed', status: 'Completed' },
    { title: '219m² Residential Unit', loc: 'Chipinge', sector: 'Residential', scope: 'Structural design for modern medium-density residential development including boundary walls', stands: 'Residential', date: 'Completed', status: 'Completed' },
    { title: 'Residential Unit (St Kelvin)', loc: 'Chipinge', sector: 'Residential', scope: 'Full structural design and construction documentation for high-end multi-bedroom dwelling', stands: 'High-End', date: 'Completed', status: 'Completed' },
    { title: 'Church Structure Foundation', loc: 'Chipinge', sector: 'Institutional', scope: 'Structural foundation design and reinforcement detailing for institutional development', stands: 'UCCZ Gaza', date: 'Completed', status: 'Completed' },
    { title: 'Structural Building Development', loc: 'Mt Selinda', sector: 'Institutional', scope: 'Comprehensive multi-storey reinforced concrete building structural design and certification', stands: 'Multi-Storey', date: 'Completed', status: 'Completed' },
  ],
  TEAM: [
    { name: 'Eng. Dereck M. Popi', role: 'Company Director', id: 'ZIE 198098 | ECZ 151080', creds: 'BSc (Hons), MBA, Pr Eng', img: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=600' },
    { name: 'Simbarashe Musakwembewa', role: 'Structural Expert', id: 'ZIE 084408 | ECZ 150285', creds: 'BSc (Hons), Pr. Eng, MECZ', img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600' },
    { name: 'Eng. Byron Muzovaka', role: 'GeoTech Expert', id: 'ZIE 144395 | ECZ 100645', creds: 'BSc (Hons), ECZ, Pr. Eng', img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600' },
    { name: 'Panashe Gora', role: 'Lead Engineer', id: 'ZIE 144446 | ECZ 100446', creds: 'BSc (Hons), ECZ, Pr. Eng, Machine Learning, Artificial Intelligence', img: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=600' },
    { name: 'Tawanda Mvarume', role: 'Civil & Water Engineer', id: 'ZIE 150410 | ECZ 120511', creds: 'BSc (Hons), Civil Design Specialist', img: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=600' },
  ],
  SCROLL_IMAGES: [
    'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=800',
    'https://images.unsplash.com/photo-1504307651254-35680f3366d4?auto=format&fit=crop&q=80&w=800',
    'https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&q=80&w=800',
    'https://images.unsplash.com/photo-1517089535819-3d8569aa83fa?auto=format&fit=crop&q=80&w=800',
    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&q=80&w=800',
    'https://images.unsplash.com/photo-1503387762-592dea58ef21?auto=format&fit=crop&q=80&w=800',
  ],
} as const;

export type Page = 'home' | 'about' | 'services' | 'projects' | 'team' | 'contact' | 'training' | 'checkout' | 'mock-payment-gateway' | 'payment-success' | 'payment-error';
